name: Python CI/CD with FastAPI

on: 
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest

      - name: Check FastAPI Import
        run: python -c "import fastapi; print('FastAPI imported successfully')"

      - name: Run FastAPI Server (background mode)
        run: uvicorn src.app:app --host 0.0.0.0 --port 8000 &

      - name: Run Tests
        run: pytest
